services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data: {}